version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install node module dependecies
          command: |
            yarn install
      - run:
          name: Run unit tests
          command: |
            ./node_modules/mocha/bin/mocha test/ --reporter mochawesome --reporter-options reportDir=test-results,reportFilename=test-results
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  build_test:
    jobs:
      - run_tests
